"""Codex TOML profile generation for session mounts."""

import json
from pathlib import Path
from typing import List, Set

from .manifest import load_pack_manifest, load_policy_index


def _toml_string(value: str) -> str:
    """JSON string escaping is compatible for normal TOML basic strings."""
    return json.dumps(value, ensure_ascii=False)


def _load_policy_text(pack_dir: Path, mount_plan: dict) -> str:
    """Load and compile policies into developer instruction text."""
    manifest = load_pack_manifest(pack_dir)
    policy_index = load_policy_index(pack_dir, manifest)

    policies = sorted(
        policy_index.get("policies", []),
        key=lambda p: p.get("priority", 0),
        reverse=True,
    )

    lines = [
        "# Illuminate Runtime Policy",
        "",
        "These instructions apply in addition to repository AGENTS.md files.",
        "",
    ]

    for policy in policies:
        policy_path = pack_dir / "policies" / policy["path"]
        if policy_path.exists():
            content = policy_path.read_text(encoding="utf-8")
            lines.append(content)
            lines.append("")

    return "\n".join(lines)


def build_codex_profile(
    *,
    repo: Path,
    session_dir: Path,
    mount_plan: dict,
    exposed_skill_ids: Set[str],
) -> str:
    """Generate a Codex TOML profile for a session mount.

    The profile embeds Illuminate Policy as developer_instructions,
    configures sandbox_mode and approval_policy, and points
    skills.config paths to the session's skill directories.
    """
    pack_dir = repo  # The pack_dir is not directly available here, but policies
                     # were already resolved at the create_mount_plan stage.
                     # We accept mount_plan which has pack info, and session_dir
                     # is where skills were already copied.
                     # The caller passes pack_dir info indirectly via mount_plan.

    # Actually, we need pack_dir for policy loading. Let's get it from mount_plan or passed separately.
    # For the current approach, we just generate the TOML structure.
    # The instructions text is generated by the caller and passed in.
    raise NotImplementedError(
        "Use build_codex_profile_content() with explicit instructions text"
    )


def build_codex_profile_content(
    *,
    repo: Path,
    session_dir: Path,
    instructions: str,
    mount_plan: dict,
    exposed_skill_ids: Set[str],
) -> str:
    """Generate a Codex TOML profile from pre-compiled instructions.

    Args:
        repo: Target repository path.
        session_dir: Session mount directory.
        instructions: Pre-compiled developer instructions text.
        mount_plan: The resolved mount plan.
        exposed_skill_ids: Set of skill IDs to include in skills.config.

    Returns:
        TOML string suitable for writing to a Codex profile file.
    """
    session_id = mount_plan["session_id"]

    pack_ref = ""
    for p in mount_plan.get("packs", []):
        pack_ref = f"{p.get('id', '?')}@{p.get('version', '?')}"

    line_comment = "# Generated by Illuminate. Do not edit."
    session_comment = f"# Session: {session_id}"
    lines = [
        line_comment,
        session_comment,
        f"# Pack: {pack_ref}",
        "",
        f"developer_instructions = {_toml_string(instructions)}",
        "",
        'approval_policy = "on-request"',
        'sandbox_mode = "workspace-write"',
        "",
        "[sandbox_workspace_write]",
        "network_access = false",
        "",
    ]

    for skill_entry in mount_plan.get("skills", {}).get("exposed", []):
        skill_id = skill_entry if isinstance(skill_entry, str) else skill_entry.get("id", "")
        if skill_id not in exposed_skill_ids:
            continue

        # Derive directory name from skill ID suffix
        skill_name = skill_id.split(".")[-1] if "." in skill_id else skill_id

        skill_path = (session_dir / ".agents" / "skills" / skill_name).resolve()

        lines.extend([
            "[[skills.config]]",
            f"path = {_toml_string(str(skill_path))}",
            "enabled = true",
            "",
        ])

    return "\n".join(lines)
