"""Knowledge Map generator for the knowledge-routing policy.

Builds a deterministic Markdown index of a target repository's knowledge
docs (docs/40-journeys, docs/70-metadata modules & components) so agents can
route to the right doc before scanning the whole codebase.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Only these two fields are consumed from module/component yaml manifests.
_ID_RE = re.compile(r"^id:\s*(.+)$")
_DOC_RE = re.compile(r"^document:\s*(.+)$")
# Journey body links pointing into docs/30-modules (forward or backslash).
_MODULE_LINK_RE = re.compile(r"\]\(docs[/\\]30-modules[/\\]([^)#]+)")
_H1_RE = re.compile(r"^#\s+(.+)$")
_H2_RE = re.compile(r"^##\s+(.+)$")

_HEADER = """# Project Knowledge Map

> Generated by Illuminate. Do not edit manually.
"""

_ROUTING = """
## How to route

- 跨模块行为：先读 Journeys
- 单模块行为：先读 Modules
- API 和生命周期：读 Components
- 状态、证据和测试：在读完正文后查询 Metadata
"""

_METADATA = """
## Metadata

- Module metadata: docs/70-metadata/modules/
- Component metadata: docs/70-metadata/components/
- Metadata is for confidence and verification, not the primary explanation.
"""


def _read_lines(path: Path) -> List[str]:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return []
    return text.splitlines()


def _first_heading(lines: List[str], pattern: re.Pattern) -> Optional[str]:
    for line in lines:
        m = pattern.match(line.strip())
        if m:
            return m.group(1).strip()
    return None


def _first_intro(lines: List[str]) -> Optional[str]:
    """First non-empty intro paragraph, skipping headings and quote lines."""
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            continue
        if stripped.startswith(">"):
            continue
        return stripped[:120]
    return None


def _headings(lines: List[str]) -> List[str]:
    result = []
    for line in lines:
        m = _H2_RE.match(line.strip())
        if m:
            result.append(m.group(1).strip())
    return result


def _clean_scalar(raw: str) -> str:
    """Strip inline YAML comment and surrounding quotes from a scalar value."""
    value = raw.strip()
    if " #" in value:
        value = value.split(" #", 1)[0]
    return value.strip().strip('"').strip("'")


def _parse_manifest(path: Path) -> Tuple[Optional[str], Optional[str]]:
    """Extract only id: and document: from a yaml manifest (no PyYAML)."""
    doc_id: Optional[str] = None
    document: Optional[str] = None
    for line in _read_lines(path):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        m = _ID_RE.match(stripped)
        if m:
            doc_id = _clean_scalar(m.group(1))
            continue
        m = _DOC_RE.match(stripped)
        if m:
            document = _clean_scalar(m.group(1)).replace("\\", "/")
    return doc_id, document


def _journeys(repo_root: Path) -> Dict[str, Dict[str, object]]:
    journeys: Dict[str, Dict[str, object]] = {}
    journeys_dir = repo_root / "docs" / "40-journeys"
    if not journeys_dir.is_dir():
        return journeys
    for path in sorted(journeys_dir.glob("*.md")):
        lines = _read_lines(path)
        title = _first_heading(lines, _H1_RE)
        if title is None:
            continue
        intro = _first_intro(lines)
        module_links = sorted(
            {
                name.strip().replace("\\", "/")
                for name in _MODULE_LINK_RE.findall("\n".join(lines))
            }
        )
        entry: Dict[str, object] = {
            "title": title,
            "file": path.name,
        }
        if intro:
            entry["intro"] = intro
        if module_links:
            entry["modules"] = module_links
        journeys[title] = entry
    return journeys


def _metadata_entries(repo_root: Path, kind: str) -> Dict[str, Dict[str, object]]:
    """Index docs/70-metadata/<kind>/*/*.yaml manifests into maps/sections."""
    entries: Dict[str, Dict[str, object]] = {}
    root = repo_root / "docs" / "70-metadata" / kind
    if not root.is_dir():
        return entries
    for yaml_path in sorted(root.glob("*/*.yaml")):
        doc_id, document = _parse_manifest(yaml_path)
        if doc_id is None or document is None:
            continue
        entry: Dict[str, object] = {"document": document}
        body = repo_root / "docs" / document
        if body.is_file():
            sections = _headings(_read_lines(body))
            if sections:
                entry["sections"] = sections
        entries[doc_id] = entry
    return entries


def _render_journeys(journeys: Dict[str, Dict[str, object]]) -> List[str]:
    out = ["## Journeys"]
    for key in sorted(journeys):
        entry = journeys[key]
        out.append(f"- {entry['title']}")
        out.append(f"  - Document: docs/40-journeys/{entry['file']}")
        if "intro" in entry:
            out.append(f"  - Covers: {entry['intro']}")
        if "modules" in entry:
            out.append(f"  - Related modules: {', '.join(entry['modules'])}")
    return out


def _render_entries(kind: str, entries: Dict[str, Dict[str, object]]) -> List[str]:
    out = [f"## {kind}"]
    for key in sorted(entries):
        entry = entries[key]
        out.append(f"- {key}")
        out.append(f"  - Document: docs/{entry['document']}")
        if "sections" in entry:
            out.append(f"  - Sections: {'、'.join(entry['sections'])}")
    return out


def build_knowledge_map(repo_root: Path) -> Optional[str]:
    """Return the Knowledge Map as Markdown, or None if there is no indexable
    knowledge in the target repository."""
    docs_dir = repo_root / "docs"
    if not docs_dir.is_dir():
        return None

    journeys = _journeys(repo_root)
    modules = _metadata_entries(repo_root, "modules")
    components = _metadata_entries(repo_root, "components")

    if not journeys and not modules and not components:
        return None

    has_entry = (repo_root / "docs" / "README-HUMAN.md").is_file()

    parts = [_HEADER]
    if has_entry:
        parts.append("\nEntry: docs/README-HUMAN.md")
    parts.append(_ROUTING)
    parts.append("\n".join(_render_journeys(journeys)))
    parts.append("")
    parts.append("\n".join(_render_entries("Modules", modules)))
    parts.append("")
    parts.append("\n".join(_render_entries("Components", components)))
    parts.append(_METADATA)
    return "\n".join(parts)


def write_knowledge_map(repo_root: Path, dest: Path) -> Optional[str]:
    """Write the Knowledge Map to ``dest`` (creating parent dirs) and return
    the map text. Returns None (and writes nothing) when the target repository
    has no indexable knowledge."""
    text = build_knowledge_map(repo_root)
    if text is None:
        return None
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text, encoding="utf-8")
    return text
