"""Knowledge Map generator for the knowledge-routing policy.

Builds a deterministic Markdown index of a target repository's knowledge
docs (docs/40-journeys, docs/70-metadata modules & components) so agents can
route to the right doc before scanning the whole codebase.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from urllib.parse import urlsplit

from .document_layout import (
    DEFAULT_HUMAN_ROOTS,
    _MANIFEST_FILES,
    is_root_relative_path,
)

# Only these two fields are consumed from module/component yaml manifests.
_ID_RE = re.compile(r"^id:\s*(.+)$")
_DOC_RE = re.compile(r"^document:\s*(.+)$")
# Local markdown link target: [text](target).
_LINK_RE = re.compile(r"\[[^\]]*\]\(([^)]+)\)")
_H1_RE = re.compile(r"^#\s+(.+)$")
_H2_RE = re.compile(r"^##\s+(.+)$")

_HEADER = """# Project Knowledge Map

> Generated by Illuminate. Do not edit manually.
"""

_ROUTING = """
## How to route

- 跨模块行为：先读 Journeys
- 单模块行为：先读 Modules
- API 和生命周期：读 Components
- 状态、证据和测试：在读完正文后查询 Metadata
"""

_METADATA = """
## Metadata

- Module metadata: docs/70-metadata/modules/
- Component metadata: docs/70-metadata/components/
- Metadata is for confidence and verification, not the primary explanation.
"""


def _read_lines(path: Path) -> List[str]:
    """Read a knowledge source's lines, fail-closed: a missing path yields no
    lines, but a path that exists and cannot be read raises instead of being
    silently treated as "no knowledge"."""
    if not path.exists():
        return []
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ValueError(f"Cannot read knowledge source: {path}: {exc}")
    return text.splitlines()


def _first_heading(lines: List[str], pattern: re.Pattern) -> Optional[str]:
    for line in lines:
        m = pattern.match(line.strip())
        if m:
            return m.group(1).strip()
    return None


def _first_intro(lines: List[str]) -> Optional[str]:
    """First non-empty intro paragraph, skipping headings and quote lines."""
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            continue
        if stripped.startswith(">"):
            continue
        return stripped[:120]
    return None


def _headings(lines: List[str]) -> List[str]:
    result = []
    for line in lines:
        m = _H2_RE.match(line.strip())
        if m:
            result.append(m.group(1).strip())
    return result


def _clean_scalar(raw: str) -> str:
    """Strip inline YAML comment and surrounding quotes from a scalar value."""
    value = raw.strip()
    if " #" in value:
        value = value.split(" #", 1)[0]
    return value.strip().strip('"').strip("'")


def _parse_manifest(path: Path) -> Tuple[Optional[str], Optional[str]]:
    """Extract only id: and document: from a yaml manifest (no PyYAML)."""
    doc_id: Optional[str] = None
    document: Optional[str] = None
    for line in _read_lines(path):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        m = _ID_RE.match(stripped)
        if m:
            doc_id = _clean_scalar(m.group(1))
            continue
        m = _DOC_RE.match(stripped)
        if m:
            document = _clean_scalar(m.group(1)).replace("\\", "/")
    return doc_id, document


def _journey_module_links(
    lines: List[str], journey_path: Path, repo_root: Path
) -> List[str]:
    """Local markdown links in a journey that resolve under docs/30-modules.

    Relative links are resolved against the journey's own directory (e.g.
    ``../30-modules/x.md`` -> ``docs/30-modules/x.md``); direct ``docs/30-modules/``
    prefix links stay supported. External URLs, mailto, and in-page anchors are
    skipped.
    """
    links = set()
    journey_dir = journey_path.parent
    docs_dir = repo_root / "docs"
    modules_root = (docs_dir / "30-modules").resolve()
    for line in lines:
        for m in _LINK_RE.finditer(line):
            raw = m.group(1).strip()
            if not raw or raw.startswith("#"):
                continue
            # Strip optional markdown title: [a](path "Title") / [a](path 'Title').
            raw = re.sub(r'\s+["\'][^"\']*["\']$', "", raw).strip()
            parsed = urlsplit(raw)
            if parsed.scheme or parsed.netloc:
                continue
            # Use the net path (query/fragment already split out by urlsplit).
            normalized = parsed.path.replace("\\", "/").strip()
            if not normalized:
                continue
            if normalized.startswith("/"):
                candidate = docs_dir / normalized.lstrip("/")
            elif normalized.startswith("docs/"):
                candidate = docs_dir / normalized[len("docs/"):]
            else:
                candidate = (journey_dir / normalized).resolve()
            try:
                rel = candidate.resolve().relative_to(modules_root)
            except ValueError:
                continue
            # A bare directory link (e.g. docs/30-modules/#sec) resolves to the
            # modules root itself; skip it instead of emitting a ghost name.
            if rel == Path("."):
                continue
            links.add(rel.as_posix())
    return sorted(links)


def _journeys(repo_root: Path) -> Dict[str, Dict[str, object]]:
    journeys: Dict[str, Dict[str, object]] = {}
    journeys_dir = repo_root / "docs" / "40-journeys"
    if not journeys_dir.is_dir():
        return journeys
    for path in sorted(journeys_dir.glob("*.md")):
        lines = _read_lines(path)
        title = _first_heading(lines, _H1_RE)
        if title is None:
            continue
        intro = _first_intro(lines)
        module_links = _journey_module_links(lines, path, repo_root)
        entry: Dict[str, object] = {
            "title": title,
            "file": path.name,
        }
        if intro:
            entry["intro"] = intro
        if module_links:
            entry["modules"] = module_links
        journeys[title] = entry
    return journeys


def _metadata_entries(repo_root: Path, kind: str) -> Dict[str, Dict[str, object]]:
    """Index docs/70-metadata/<kind>/*/<manifest>.yaml manifests into maps.

    Only the exact manifest filename for the kind is globbed (module.yaml /
    component.yaml), and each manifest's root-relative document must resolve
    under the kind's human doc root (docs/30-modules/ or docs/20-components/).
    Entries that fail validation are skipped, matching the existing
    missing-id/document skip behavior.
    """
    entries: Dict[str, Dict[str, object]] = {}
    root = repo_root / "docs" / "70-metadata" / kind
    if not root.is_dir():
        return entries
    expected_root = DEFAULT_HUMAN_ROOTS[kind]
    layout = {"human_roots": DEFAULT_HUMAN_ROOTS}
    for yaml_path in sorted(root.glob(f"*/{_MANIFEST_FILES[kind]}")):
        doc_id, document = _parse_manifest(yaml_path)
        if doc_id is None or document is None:
            continue
        if (
            not is_root_relative_path(document, layout)
            or Path(document).parts[0] != expected_root
        ):
            continue
        entry: Dict[str, object] = {"document": document}
        body = repo_root / "docs" / document
        if body.is_file():
            sections = _headings(_read_lines(body))
            if sections:
                entry["sections"] = sections
        entries[doc_id] = entry
    return entries


def _render_journeys(journeys: Dict[str, Dict[str, object]]) -> List[str]:
    out = ["## Journeys"]
    for key in sorted(journeys):
        entry = journeys[key]
        out.append(f"- {entry['title']}")
        out.append(f"  - Document: docs/40-journeys/{entry['file']}")
        if "intro" in entry:
            out.append(f"  - Covers: {entry['intro']}")
        if "modules" in entry:
            out.append(f"  - Related modules: {', '.join(entry['modules'])}")
    return out


def _render_entries(kind: str, entries: Dict[str, Dict[str, object]]) -> List[str]:
    out = [f"## {kind}"]
    for key in sorted(entries):
        entry = entries[key]
        out.append(f"- {key}")
        out.append(f"  - Document: docs/{entry['document']}")
        if "sections" in entry:
            out.append(f"  - Sections: {'、'.join(entry['sections'])}")
    return out


def build_knowledge_map(repo_root: Path) -> Optional[str]:
    """Return the Knowledge Map as Markdown, or None if there is no indexable
    knowledge in the target repository."""
    docs_dir = repo_root / "docs"
    if not docs_dir.is_dir():
        return None

    journeys = _journeys(repo_root)
    modules = _metadata_entries(repo_root, "modules")
    components = _metadata_entries(repo_root, "components")

    if not journeys and not modules and not components:
        return None

    has_entry = (repo_root / "docs" / "README-HUMAN.md").is_file()

    parts = [_HEADER]
    if has_entry:
        parts.append("\nEntry: docs/README-HUMAN.md")
    parts.append(_ROUTING)
    parts.append("\n".join(_render_journeys(journeys)))
    parts.append("")
    parts.append("\n".join(_render_entries("Modules", modules)))
    parts.append("")
    parts.append("\n".join(_render_entries("Components", components)))
    parts.append(_METADATA)
    return "\n".join(parts)


def write_knowledge_map(repo_root: Path, dest: Path) -> Optional[str]:
    """Write the Knowledge Map to ``dest`` (creating parent dirs) and return
    the map text. Returns None (and writes nothing) when the target repository
    has no indexable knowledge."""
    text = build_knowledge_map(repo_root)
    if text is None:
        return None
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text, encoding="utf-8")
    return text


# --- Behavior-level routing (first-round read order) -------------------------
# Mirrors the Knowledge Map "How to route" section: cross-module -> Journeys,
# single-module -> Modules, API/lifecycle -> Components, and status/evidence ->
# Metadata after the body.

_VERIFY_RE = re.compile(
    r"验证|已验证|结论|verified|verification|evidence|是否(成立|已验证|被验证)|可信"
)


def _matches(req: str, keywords: List[str]) -> bool:
    return any(kw and kw.lower() in req for kw in keywords)


def _first_match_id(req: str, docs: List[Dict[str, object]], key: str) -> Optional[str]:
    for d in docs:
        if _matches(req, [str(d.get(key, ""))]):
            return d.get(key)
    return None


def route_read_order(request: str, knowledge_state: Dict[str, object]) -> List[str]:
    """Return the recommended first-round read sequence for ``request`` against
    a target repo's ``knowledge_state``.

    ``knowledge_state`` is derived from the generated Knowledge Map (see
    ``build_knowledge_map``) and uses these keys::

        has_map     - bool, whether a Knowledge Map exists
        journeys    - [{"title", "modules": [module_id, ...]}]
        modules     - [{"id"}]
        components  - [{"id"}]

    Matching is derived purely from map-native fields (journey ``title`` and
    module/component ``id``); the map carries no free-form keyword list.

    Step kinds: ``map``, ``journey``, ``module``, ``component``, ``metadata``,
    ``docs``, ``source``.

    Policy:
      - map first (when present), then:
          * cross-module -> matching Journey, then its linked Modules;
          * status/evidence/verification -> module正文 then Metadata;
          * API / lifecycle -> matching Component;
          * single-module -> matching Module;
      - matched knowledge routes without a map (no "map" step);
      - no matched knowledge -> docs/source, never retry the missing map.
    """
    req = request.lower()

    steps: List[str] = ["map"] if knowledge_state.get("has_map") else []
    module_ids = {d.get("id") for d in knowledge_state.get("modules") or []}

    # Cross-module behavior first (policy rule 3): matching Journey, then its
    # linked Modules that actually exist in the index.
    for journey in knowledge_state.get("journeys") or []:
        if _matches(req, [str(journey.get("title", ""))]):
            steps.append("journey")
            if journey.get("modules") and any(
                mid in module_ids for mid in journey["modules"]
            ):
                steps.append("module")
            return steps

    # Status/evidence/verification -> module body then Metadata. Checked after
    # Journey so a cross-module request with verify wording still reads the
    # Journey first (policy rule 3).
    if _VERIFY_RE.search(req):
        steps.append("module")
        steps.append("metadata")
        return steps

    # API / lifecycle -> Component (policy rule 2). Checked before Module so a
    # specific component/lifecycle request is not shadowed by a module keyword.
    if _first_match_id(req, knowledge_state.get("components") or [], "id"):
        steps.append("component")
        return steps

    if _first_match_id(req, knowledge_state.get("modules") or [], "id"):
        steps.append("module")
        return steps

    # No matched knowledge. Even without a map, matched knowledge above would
    # have returned; only here do we fall back to scanning docs/source.
    if not knowledge_state.get("has_map"):
        return ["docs", "source"]
    steps.extend(["docs", "source"])
    return steps
