"""Knowledge Map end-to-end sync tests across the harness adapters.

Covers the acceptance contract for the knowledge-routing integration:
  - a repo with no docs/ produces no map file and no map hash, and check
    reports no map error;
  - a repo with a minimal docs/ layout produces .illuminate/knowledge-map.md
    containing the map header, and check passes;
  - when the repo's knowledge changes after sync, check must flag the map as
    stale (hash mismatch / missing map) instead of silently passing.

The map file and its lock hash are generated by the harness sync; the cursor
adapter is the primary surface exercised here.
"""

import json
import os
import shutil
import stat
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from illuminate.materialize_claude import materialize_session
from illuminate.sync_codebuddy import (
    check_sync as check_codebuddy,
    clean_sync as clean_codebuddy,
    sync_codebuddy,
)
from illuminate.sync_codex import (
    check_sync as check_codex,
    clean_sync as clean_codex,
    sync_codex,
)
from illuminate.sync_cursor import check_sync, clean_sync, sync_cursor

REPO_ROOT = Path(__file__).parent.parent
CORE_PACK = REPO_ROOT / "packs" / "core"

MAP_REL = ".illuminate/knowledge-map.md"


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _set_readonly(path: Path) -> None:
    """Make a file read-only on both Windows (attribute) and POSIX (mode)."""
    os.chmod(path, stat.S_IREAD | stat.S_IRGRP | stat.S_IROTH)


def _make_writable(path: Path) -> None:
    """Restore write permission so tempdir cleanup does not fail."""
    os.chmod(path, stat.S_IWRITE | stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)


class TestKnowledgeMapSync(unittest.TestCase):

    def setUp(self):
        self.tmpdir = Path(tempfile.mkdtemp())

    def _make_repo(self, sub: str = "target-repo") -> Path:
        repo = self.tmpdir / sub
        repo.mkdir(parents=True, exist_ok=True)
        return repo

    def test_no_docs_repo_has_no_map_and_check_has_no_map_error(self):
        """A repo with no docs/ yields no knowledge map file, no map hash in
        the lock, and a passing check (no map-related error)."""
        repo = self._make_repo()
        sync_cursor(CORE_PACK, repo)

        self.assertFalse((repo / MAP_REL).exists())
        lock = (repo / ".illuminate" / "cursor-lock.json")
        import json
        lock_data = json.loads(lock.read_text(encoding="utf-8"))
        self.assertNotIn("knowledge_map_hash", lock_data)

        ok, issues = check_sync(CORE_PACK, repo)
        self.assertTrue(ok, f"Check should pass with no docs: {issues}")
        self.assertFalse(
            any("knowledge map" in i.lower() or "Knowledge map" in i for i in issues),
            issues,
        )

    def test_docs_repo_writes_map_and_check_passes(self):
        """A minimal docs/ layout produces a knowledge map containing the
        map header, and check_sync passes."""
        repo = self._make_repo()
        _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")

        sync_cursor(CORE_PACK, repo)

        map_path = repo / MAP_REL
        self.assertTrue(map_path.exists())
        content = map_path.read_text(encoding="utf-8")
        self.assertIn("Project Knowledge Map", content)
        self.assertIn("Journey A", content)

        ok, issues = check_sync(CORE_PACK, repo)
        self.assertTrue(ok, f"Check should pass with docs: {issues}")

    def test_doc_change_after_sync_is_flagged_stale(self):
        """Adding a journey doc after sync makes the knowledge stale; check_sync
        must flag a map hash mismatch (or an equivalent stale signal) instead of
        silently passing."""
        repo = self._make_repo()
        _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
        sync_cursor(CORE_PACK, repo)
        ok, _ = check_sync(CORE_PACK, repo)
        self.assertTrue(ok)

        # New knowledge appears after sync -> the map is now stale.
        _write(repo / "docs" / "40-journeys" / "b.md", "# Journey B\n\nother behavior.\n")

        ok, issues = check_sync(CORE_PACK, repo)
        self.assertFalse(ok, f"Check must flag stale knowledge: {issues}")
        self.assertTrue(
            any("hash mismatch" in i and "knowledge map" in i.lower() for i in issues)
            or any("knowledge map" in i.lower() and "mismatch" in i.lower() for i in issues),
            f"Expected a stale-map signal in: {issues}",
        )

    def test_resync_after_doc_change_regenerates_and_passes(self):
        """Re-syncing after a doc change regenerates the map and restores a
        passing check."""
        repo = self._make_repo()
        _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
        sync_cursor(CORE_PACK, repo)

        _write(repo / "docs" / "40-journeys" / "b.md", "# Journey B\n\nother behavior.\n")
        sync_cursor(CORE_PACK, repo)

        content = (repo / MAP_REL).read_text(encoding="utf-8")
        self.assertIn("Journey B", content)
        ok, issues = check_sync(CORE_PACK, repo)
        self.assertTrue(ok, f"Check should pass after re-sync: {issues}")

    def test_codex_and_codebuddy_flag_stale_equivalently(self):
        """codex and codebuddy flag a docs change after sync with the same
        stale signal as cursor (three-harness equivalence)."""
        for name, sync_fn, check_fn in (
            ("codex", sync_codex, check_codex),
            ("codebuddy", sync_codebuddy, check_codebuddy),
        ):
            with self.subTest(adapter=name):
                repo = self._make_repo(name)
                _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
                sync_fn(CORE_PACK, repo)
                ok, _ = check_fn(CORE_PACK, repo)
                self.assertTrue(ok, f"{name} check should pass after sync")

                _write(repo / "docs" / "40-journeys" / "b.md", "# Journey B\n\nmore.\n")
                ok, issues = check_fn(CORE_PACK, repo)
                self.assertFalse(ok, f"{name} must flag stale knowledge: {issues}")
                self.assertTrue(
                    any(
                        "knowledge map" in i.lower() and "mismatch" in i.lower()
                        for i in issues
                    ),
                    f"{name} missing stale-map signal in: {issues}",
                )

    def test_clean_removes_map_across_adapters(self):
        """clean_sync removes .illuminate/knowledge-map.md on every adapter
        that records a map hash (cross-adapter clean consistency)."""
        for name, sync_fn, clean_fn in (
            ("cursor", sync_cursor, clean_sync),
            ("codex", sync_codex, clean_codex),
            ("codebuddy", sync_codebuddy, clean_codebuddy),
        ):
            with self.subTest(adapter=name):
                repo = self._make_repo(name)
                _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
                sync_fn(CORE_PACK, repo)
                self.assertTrue((repo / MAP_REL).exists())
                clean_fn(repo)
                self.assertFalse(
                    (repo / MAP_REL).exists(), f"{name} left orphan knowledge map"
                )

    def test_materialize_with_docs_writes_session_map_only(self):
        """materialize_session against a repo with docs must generate the map
        in the session dir (never the target repo) and register it in the
        lock's managed artifacts."""
        repo = self._make_repo()
        _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
        info = materialize_session(CORE_PACK, str(repo))
        session_dir = Path(info["session_dir"])
        map_path = session_dir / "project-knowledge-map.md"
        self.assertTrue(map_path.exists())
        self.assertIn("Project Knowledge Map", map_path.read_text(encoding="utf-8"))
        self.assertIn(
            "project-knowledge-map.md",
            info["lock"].get("managed_artifacts", []),
        )
        self.assertFalse((repo / MAP_REL).exists(), "map must stay out of the repo")

    # ── P0-1: multi-harness shared map clean ──

    def test_clean_cursor_preserves_map_for_codex(self):
        """Cleaning Cursor while Codex still owns the shared map must keep the
        map and leave Codex's check passing."""
        repo = self._make_repo()
        _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
        sync_cursor(CORE_PACK, repo)
        sync_codex(CORE_PACK, repo)
        self.assertTrue((repo / MAP_REL).exists())

        clean_sync(repo)  # cursor clean

        self.assertTrue(
            (repo / MAP_REL).exists(),
            "Map must survive Cursor clean while Codex still owns it",
        )
        ok, issues = check_codex(CORE_PACK, repo)
        self.assertTrue(ok, f"Codex check must pass after Cursor clean: {issues}")

        clean_codex(repo)  # now no harness owns the map -> it is removed
        self.assertFalse((repo / MAP_REL).exists())

    def test_clean_codex_preserves_map_for_cursor(self):
        """The reverse ordering: cleaning Codex while Cursor still owns the
        shared map must keep it and leave Cursor's check passing."""
        repo = self._make_repo()
        _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
        sync_codex(CORE_PACK, repo)
        sync_cursor(CORE_PACK, repo)

        clean_codex(repo)  # codex clean

        self.assertTrue(
            (repo / MAP_REL).exists(),
            "Map must survive Codex clean while Cursor still owns it",
        )
        ok, issues = check_sync(CORE_PACK, repo)
        self.assertTrue(ok, f"Cursor check must pass after Codex clean: {issues}")

    # ── P0-2: present/absent state transitions ──

    def test_first_doc_appearing_after_sync_flags_stale(self):
        """无→有: a repo synced with no docs, then given its first doc, must be
        flagged stale on check (the lock records no map but one is now
        derivable), forcing a re-sync."""
        repo = self._make_repo()
        sync_cursor(CORE_PACK, repo)
        ok, _ = check_sync(CORE_PACK, repo)
        self.assertTrue(ok)

        _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
        ok, issues = check_sync(CORE_PACK, repo)
        self.assertFalse(ok, f"Must flag stale when first doc appears: {issues}")
        self.assertTrue(
            any("now derivable" in i for i in issues),
            f"Expected a now-derivable stale signal in: {issues}",
        )

    def test_remove_all_docs_resync_deletes_map_and_check_healthy(self):
        """有→无: after all docs are removed, re-sync deletes the stale map
        file, drops the map hash from the lock, and check is healthy."""
        repo = self._make_repo()
        _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
        sync_cursor(CORE_PACK, repo)
        self.assertTrue((repo / MAP_REL).exists())

        shutil.rmtree(repo / "docs")
        sync_cursor(CORE_PACK, repo)

        self.assertFalse(
            (repo / MAP_REL).exists(), "Stale map must be deleted on re-sync"
        )
        lock = json.loads(
            (repo / ".illuminate" / "cursor-lock.json").read_text(encoding="utf-8")
        )
        self.assertNotIn("knowledge_map_hash", lock)
        ok, issues = check_sync(CORE_PACK, repo)
        self.assertTrue(ok, f"Check must pass with no docs and no map: {issues}")

    # ── P0-3: map write/delete in preflight ──

    def test_readonly_map_fails_before_any_write(self):
        """A read-only knowledge-map.md must abort sync in preflight, leaving
        no partial write (map and lock untouched)."""
        repo = self._make_repo()
        _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
        sync_cursor(CORE_PACK, repo)
        map_path = repo / MAP_REL
        self.assertTrue(map_path.exists())
        map_before = map_path.read_text(encoding="utf-8")
        lock_before = (repo / ".illuminate" / "cursor-lock.json").read_bytes()
        _set_readonly(map_path)
        try:
            with self.assertRaises(ValueError):
                sync_cursor(CORE_PACK, repo)
            self.assertEqual(
                map_path.read_text(encoding="utf-8"), map_before,
                "Read-only map must not be overwritten by a failed sync",
            )
            self.assertEqual(
                (repo / ".illuminate" / "cursor-lock.json").read_bytes(),
                lock_before,
                "Lock must be unchanged by a failed sync",
            )
        finally:
            _make_writable(map_path)

    # ── P1-1: tampered disk map ──

    def test_tampered_map_file_is_flagged(self):
        """A knowledge map file whose on-disk content is edited/tampered must
        be flagged as a file hash mismatch."""
        repo = self._make_repo()
        _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
        sync_cursor(CORE_PACK, repo)
        ok, _ = check_sync(CORE_PACK, repo)
        self.assertTrue(ok)

        (repo / MAP_REL).write_text("# Tampered map\n", encoding="utf-8")
        ok, issues = check_sync(CORE_PACK, repo)
        self.assertFalse(ok)
        self.assertTrue(
            any("file hash mismatch" in i for i in issues),
            f"Expected a tamper signal in: {issues}",
        )


    # ── P1-2: fail-safe clean on a corrupt other-harness lock ──

    def test_clean_cursor_keeps_map_when_codex_lock_corrupt(self):
        """If a remaining harness's lock is corrupt (cannot prove whether it
        still owns the shared map), clean must NOT delete the map — fail-safe
        toward keeping a shared artifact it cannot verify is unowned."""
        repo = self._make_repo()
        _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
        sync_cursor(CORE_PACK, repo)
        sync_codex(CORE_PACK, repo)
        self.assertTrue((repo / MAP_REL).exists())

        # Corrupt the codex lock so it cannot be parsed.
        (repo / ".illuminate" / "codex-lock.json").write_text(
            "{ this is not valid json", encoding="utf-8"
        )

        clean_sync(repo)  # cursor clean

        self.assertTrue(
            (repo / MAP_REL).exists(),
            "Map must survive Cursor clean when Codex's lock is corrupt",
        )

    # ── P1-3: healthy state flags an orphan on-disk map ──

    def test_check_flags_orphan_map_when_lock_expects_none(self):
        """A map file on disk that the lock does not expect (and cannot be
        derived) must be flagged stale/error instead of a silent healthy pass,
        since PROJECT_KNOWLEDGE_BLOCK reads it whenever it exists."""
        repo = self._make_repo()
        sync_cursor(CORE_PACK, repo)  # no docs -> no map, lock has no hash
        self.assertFalse((repo / MAP_REL).exists())

        _write(repo / MAP_REL, "# Stale orphan map\n")

        ok, issues = check_sync(CORE_PACK, repo)
        self.assertFalse(ok, f"Orphan map must be flagged: {issues}")
        self.assertTrue(
            any("Knowledge map present" in i for i in issues),
            f"Expected an orphan-map stale signal in: {issues}",
        )

    # ── P1-4: resync preserves a hand-placed map ──

    def test_resync_keeps_hand_placed_map_not_recorded_in_any_lock(self):
        """A .illuminate/knowledge-map.md that no Illuminate sync ever created
        (no lock records a knowledge_map_hash) must be preserved on resync, not
        unlinked — Illuminate only deletes files it owns."""
        repo = self._make_repo()
        sync_cursor(CORE_PACK, repo)  # no docs -> lock records no map hash
        _write(repo / MAP_REL, "# Hand-placed map\n")

        sync_cursor(CORE_PACK, repo)  # resync with no docs

        self.assertTrue(
            (repo / MAP_REL).exists(),
            "Hand-placed map must survive a resync that records no ownership",
        )
        self.assertEqual(
            (repo / MAP_REL).read_text(encoding="utf-8"), "# Hand-placed map\n"
        )

    def test_resync_deletes_map_when_lock_records_ownership(self):
        """A stale map that Illuminate previously created (a lock records its
        hash) is still deleted on resync after docs are removed — ownership is
        the deciding factor, not mere existence."""
        repo = self._make_repo()
        _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
        sync_cursor(CORE_PACK, repo)
        self.assertTrue((repo / MAP_REL).exists())

        shutil.rmtree(repo / "docs")
        sync_cursor(CORE_PACK, repo)

        self.assertFalse(
            (repo / MAP_REL).exists(),
            "Owned stale map must still be deleted on resync after docs removed",
        )


if __name__ == "__main__":
    unittest.main()
