"""Knowledge Map end-to-end sync tests across the harness adapters.

Covers the acceptance contract for the knowledge-routing integration:
  - a repo with no docs/ produces no map file and no map hash, and check
    reports no map error;
  - a repo with a minimal docs/ layout produces .illuminate/knowledge-map.md
    containing the map header, and check passes;
  - when the repo's knowledge changes after sync, check must flag the map as
    stale (hash mismatch / missing map) instead of silently passing.

The map file and its lock hash are generated by the harness sync; the cursor
adapter is the primary surface exercised here.
"""

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from illuminate.materialize_claude import materialize_session
from illuminate.sync_codebuddy import (
    check_sync as check_codebuddy,
    clean_sync as clean_codebuddy,
    sync_codebuddy,
)
from illuminate.sync_codex import (
    check_sync as check_codex,
    clean_sync as clean_codex,
    sync_codex,
)
from illuminate.sync_cursor import check_sync, clean_sync, sync_cursor

REPO_ROOT = Path(__file__).parent.parent
CORE_PACK = REPO_ROOT / "packs" / "core"

MAP_REL = ".illuminate/knowledge-map.md"


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


class TestKnowledgeMapSync(unittest.TestCase):

    def setUp(self):
        self.tmpdir = Path(tempfile.mkdtemp())

    def _make_repo(self, sub: str = "target-repo") -> Path:
        repo = self.tmpdir / sub
        repo.mkdir(parents=True, exist_ok=True)
        return repo

    def test_no_docs_repo_has_no_map_and_check_has_no_map_error(self):
        """A repo with no docs/ yields no knowledge map file, no map hash in
        the lock, and a passing check (no map-related error)."""
        repo = self._make_repo()
        sync_cursor(CORE_PACK, repo)

        self.assertFalse((repo / MAP_REL).exists())
        lock = (repo / ".illuminate" / "cursor-lock.json")
        import json
        lock_data = json.loads(lock.read_text(encoding="utf-8"))
        self.assertNotIn("knowledge_map_hash", lock_data)

        ok, issues = check_sync(CORE_PACK, repo)
        self.assertTrue(ok, f"Check should pass with no docs: {issues}")
        self.assertFalse(
            any("knowledge map" in i.lower() or "Knowledge map" in i for i in issues),
            issues,
        )

    def test_docs_repo_writes_map_and_check_passes(self):
        """A minimal docs/ layout produces a knowledge map containing the
        map header, and check_sync passes."""
        repo = self._make_repo()
        _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")

        sync_cursor(CORE_PACK, repo)

        map_path = repo / MAP_REL
        self.assertTrue(map_path.exists())
        content = map_path.read_text(encoding="utf-8")
        self.assertIn("Project Knowledge Map", content)
        self.assertIn("Journey A", content)

        ok, issues = check_sync(CORE_PACK, repo)
        self.assertTrue(ok, f"Check should pass with docs: {issues}")

    def test_doc_change_after_sync_is_flagged_stale(self):
        """Adding a journey doc after sync makes the knowledge stale; check_sync
        must flag a map hash mismatch (or an equivalent stale signal) instead of
        silently passing."""
        repo = self._make_repo()
        _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
        sync_cursor(CORE_PACK, repo)
        ok, _ = check_sync(CORE_PACK, repo)
        self.assertTrue(ok)

        # New knowledge appears after sync -> the map is now stale.
        _write(repo / "docs" / "40-journeys" / "b.md", "# Journey B\n\nother behavior.\n")

        ok, issues = check_sync(CORE_PACK, repo)
        self.assertFalse(ok, f"Check must flag stale knowledge: {issues}")
        self.assertTrue(
            any("hash mismatch" in i and "knowledge map" in i.lower() for i in issues)
            or any("knowledge map" in i.lower() and "mismatch" in i.lower() for i in issues),
            f"Expected a stale-map signal in: {issues}",
        )

    def test_resync_after_doc_change_regenerates_and_passes(self):
        """Re-syncing after a doc change regenerates the map and restores a
        passing check."""
        repo = self._make_repo()
        _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
        sync_cursor(CORE_PACK, repo)

        _write(repo / "docs" / "40-journeys" / "b.md", "# Journey B\n\nother behavior.\n")
        sync_cursor(CORE_PACK, repo)

        content = (repo / MAP_REL).read_text(encoding="utf-8")
        self.assertIn("Journey B", content)
        ok, issues = check_sync(CORE_PACK, repo)
        self.assertTrue(ok, f"Check should pass after re-sync: {issues}")

    def test_codex_and_codebuddy_flag_stale_equivalently(self):
        """codex and codebuddy flag a docs change after sync with the same
        stale signal as cursor (three-harness equivalence)."""
        for name, sync_fn, check_fn in (
            ("codex", sync_codex, check_codex),
            ("codebuddy", sync_codebuddy, check_codebuddy),
        ):
            with self.subTest(adapter=name):
                repo = self._make_repo(name)
                _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
                sync_fn(CORE_PACK, repo)
                ok, _ = check_fn(CORE_PACK, repo)
                self.assertTrue(ok, f"{name} check should pass after sync")

                _write(repo / "docs" / "40-journeys" / "b.md", "# Journey B\n\nmore.\n")
                ok, issues = check_fn(CORE_PACK, repo)
                self.assertFalse(ok, f"{name} must flag stale knowledge: {issues}")
                self.assertTrue(
                    any(
                        "knowledge map" in i.lower() and "mismatch" in i.lower()
                        for i in issues
                    ),
                    f"{name} missing stale-map signal in: {issues}",
                )

    def test_clean_removes_map_across_adapters(self):
        """clean_sync removes .illuminate/knowledge-map.md on every adapter
        that records a map hash (cross-adapter clean consistency)."""
        for name, sync_fn, clean_fn in (
            ("cursor", sync_cursor, clean_sync),
            ("codex", sync_codex, clean_codex),
            ("codebuddy", sync_codebuddy, clean_codebuddy),
        ):
            with self.subTest(adapter=name):
                repo = self._make_repo(name)
                _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
                sync_fn(CORE_PACK, repo)
                self.assertTrue((repo / MAP_REL).exists())
                clean_fn(repo)
                self.assertFalse(
                    (repo / MAP_REL).exists(), f"{name} left orphan knowledge map"
                )

    def test_materialize_with_docs_writes_session_map_only(self):
        """materialize_session against a repo with docs must generate the map
        in the session dir (never the target repo) and register it in the
        lock's managed artifacts."""
        repo = self._make_repo()
        _write(repo / "docs" / "40-journeys" / "a.md", "# Journey A\n\ncross-module.\n")
        info = materialize_session(CORE_PACK, str(repo))
        session_dir = Path(info["session_dir"])
        map_path = session_dir / "project-knowledge-map.md"
        self.assertTrue(map_path.exists())
        self.assertIn("Project Knowledge Map", map_path.read_text(encoding="utf-8"))
        self.assertIn(
            "project-knowledge-map.md",
            info["lock"].get("managed_artifacts", []),
        )
        self.assertFalse((repo / MAP_REL).exists(), "map must stay out of the repo")


if __name__ == "__main__":
    unittest.main()
